name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5

  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      lib_changed: ${{ steps.check-libs.outputs.lib_changed }}
      playground_changed: ${{ steps.check-playground.outputs.playground_changed }}
      storybook_changed: ${{ steps.check-storybook.outputs.storybook_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --legacy-peer-deps

      # Check for library changes (excluding stories files)
      - name: Check for library changes
        id: check-libs
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

          # Check if library files changed (excluding .stories.ts)
          if grep -q "^libs/ngx-tailwind-flex-ui/" changed_files.txt | grep -v ".stories.ts"; then
            echo "lib_changed=true" >> $GITHUB_OUTPUT
            echo "Library files changed"
          else
            echo "lib_changed=false" >> $GITHUB_OUTPUT
            echo "No library files changed"
          fi

      # Check for playground app changes
      - name: Check for playground changes
        id: check-playground
        run: |
          if grep -q "^apps/playground/" changed_files.txt; then
            echo "playground_changed=true" >> $GITHUB_OUTPUT
            echo "Playground app files changed"
          else
            echo "playground_changed=false" >> $GITHUB_OUTPUT
            echo "No playground app files changed"
          fi

      # Check for storybook changes
      - name: Check for storybook changes
        id: check-storybook
        run: |
          if grep -q "libs/ngx-tailwind-flex-ui/.storybook/" changed_files.txt || grep -q "libs/ngx-tailwind-flex-ui/.*\.stories\.ts" changed_files.txt; then
            echo "storybook_changed=true" >> $GITHUB_OUTPUT
            echo "Storybook files changed"
          else
            echo "storybook_changed=false" >> $GITHUB_OUTPUT
            echo "No storybook files changed"
          fi

  build-test:
    runs-on: ubuntu-latest
    needs: [commit-lint, determine-changes]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps
      - run: npx nx affected -t lint test build e2e

  canary-release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.determine-changes.outputs.lib_changed == 'true' }}
    needs: [build-test, determine-changes]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci --legacy-peer-deps
      - name: Publish Canary Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  label-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto-label PRs
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'

  dependabot-auto-merge:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target: minor

  deploy-storybook:
    needs: [build-test, determine-changes]
    if: ${{ github.ref == 'refs/heads/main' && (needs.determine-changes.outputs.storybook_changed == 'true' || needs.determine-changes.outputs.lib_changed == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - name: Build Storybook
        run: npx nx run ngx-tailwind-flex-ui:build-storybook
      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist/storybook/ngx-tailwind-flex-ui
          destination_dir: docs
          keep_files: true

  deploy-playground:
    needs: [build-test, determine-changes]
    if: ${{ github.ref == 'refs/heads/main' && (needs.determine-changes.outputs.playground_changed == 'true' || needs.determine-changes.outputs.lib_changed == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - name: Build Playground App
        run: npx nx build playground --base-href=/ngx-tailwind-flex-ui/playground/
      - name: Deploy Playground to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist/apps/playground
          destination_dir: playground
          keep_files: true
